# Generated by Django 4.0.3 on 2022-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=300)),
                ('profile_photo', models.ImageField(upload_to='profile_photo/%Y/%m/%d/')),
                ('cover_photo', models.ImageField(upload_to='cover_photo/%Y/%m/%d/')),
                ('profession', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('job_title', models.CharField(max_length=300)),
                ('employer', models.CharField(max_length=300)),
                ('job_city', models.CharField(max_length=300)),
                ('job_country', models.CharField(max_length=300)),
                ('job_start_date', models.CharField(max_length=300)),
                ('job_end_date', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
                ('school_name', models.CharField(max_length=300)),
                ('school_location', models.CharField(max_length=300)),
                ('degree', models.CharField(max_length=300)),
                ('field_of_study', models.CharField(max_length=300)),
                ('school_start_date', models.CharField(max_length=300)),
                ('school_end_date', models.CharField(max_length=300)),
                ('skills', models.TextField()),
                ('project_title', models.CharField(max_length=300)),
                ('project_date', models.CharField(max_length=300)),
                ('project_description', models.TextField()),
                ('website', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('linkedin', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
