# Generated by Django 4.0.3 on 2022-03-21 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_buildresume_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildresume',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
