# Generated by Django 4.0.3 on 2022-03-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_buildresume_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildresume',
            name='about_you',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
