# Generated by Django 4.0.3 on 2022-03-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_buildresume_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildresume',
            name='resume_title',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
