# Generated by Django 4.0.3 on 2022-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_templatename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildresume',
            old_name='degree',
            new_name='award_date_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='employer',
            new_name='award_date_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_description',
            new_name='award_description_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='project_description',
            new_name='award_description_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='field_of_study',
            new_name='award_title_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_city',
            new_name='award_title_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_country',
            new_name='company_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_end_date',
            new_name='company_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_start_date',
            new_name='field_of_study_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='job_title',
            new_name='field_of_study_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='project_date',
            new_name='job_city_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='project_title',
            new_name='job_city_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='school_end_date',
            new_name='job_country_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='school_location',
            new_name='job_country_2',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='school_name',
            new_name='job_end_date_1',
        ),
        migrations.RenameField(
            model_name='buildresume',
            old_name='school_start_date',
            new_name='job_end_date_2',
        ),
        migrations.RemoveField(
            model_name='buildresume',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='buildresume',
            name='interests',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='job_description_1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='job_description_2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='job_start_date_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='job_start_date_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_date_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_date_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_description_1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_description_2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_title_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='project_title_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='role_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='role_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_end_date_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_end_date_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_name_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_name_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_start_date_1',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='school_start_date_2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='speaking_languages',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
