# Generated by Django 4.0.3 on 2022-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_degree_buildresume_award_date_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildresume',
            name='first_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='last_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildresume',
            name='username',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
