# Generated by Django 4.0.3 on 2022-03-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_buildresume_first_name_buildresume_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildresume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buildresume',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='buildresume',
            name='username',
        ),
    ]
